version: '3.3'
services:
  neo4j:
    image: neo4j
    ports:
      - 7687:7687 
      - 7474:7474 
    volumes:
      - ./volume_mount/data:/data
      - ./volume_mount/logs:/logs


networks: 
  default:
    external: 
      name: registry_default