version: '3.3'
services:
  kibana:
    #image: docker.elastic.co/kibana/kibana:7.8.0
    image: docker.elastic.co/kibana/kibana:6.8.10
    ports:
      - 5601:5601
    volumes:
      - ./volume_mount/data/config:/usr/share/kibana/config


networks: 
  default:
    external: 
      name: registry_default