version: '3'

services:
  portainer:
    image: portainer/portainer:latest
    restart: always
    container_name: portainer
    environment:
      - no-auth
    ports:
      - "9000:9000"
    volumes:
      - ./volume_mount:/var/run/docker.sock
      - ./volume_mount:/data

volumes:
  portainer:
